// Code generated by go-swagger; DO NOT EDIT.

package backups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDReader is a Reader for the DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsID structure.
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}] delete_organizations_organization_databases_database_branches_branch_backups_id", response, response.Code())
	}
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent describes a response with status code 204, with default header values.

Delete a backup
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches branch backups Id no content response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete organizations organization databases database branches branch backups Id no content response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches branch backups Id no content response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organizations organization databases database branches branch backups Id no content response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches branch backups Id no content response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete organizations organization databases database branches branch backups Id no content response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) Code() int {
	return 204
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdNoContent ", 204)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdNoContent ", 204)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches branch backups Id unauthorized response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches branch backups Id unauthorized response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches branch backups Id unauthorized response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches branch backups Id unauthorized response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches branch backups Id unauthorized response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete organizations organization databases database branches branch backups Id unauthorized response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdUnauthorized ", 401)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdUnauthorized ", 401)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches branch backups Id forbidden response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches branch backups Id forbidden response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches branch backups Id forbidden response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches branch backups Id forbidden response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches branch backups Id forbidden response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete organizations organization databases database branches branch backups Id forbidden response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) Code() int {
	return 403
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdForbidden ", 403)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdForbidden ", 403)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches branch backups Id not found response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches branch backups Id not found response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches branch backups Id not found response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches branch backups Id not found response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches branch backups Id not found response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete organizations organization databases database branches branch backups Id not found response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) Code() int {
	return 404
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdNotFound ", 404)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdNotFound ", 404)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches branch backups Id internal server error response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches branch backups Id internal server error response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches branch backups Id internal server error response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organizations organization databases database branches branch backups Id internal server error response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete organizations organization databases database branches branch backups Id internal server error response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete organizations organization databases database branches branch backups Id internal server error response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdInternalServerError ", 500)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{branch}/backups/{id}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIdInternalServerError ", 500)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
