// Code generated by go-swagger; DO NOT EDIT.

package backups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams() *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithTimeout creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams{
		timeout: timeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithContext creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams object
// with the ability to set a context for a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams{
		Context: ctx,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithHTTPClient creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParamsWithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams contains all the parameters to send to the API endpoint

	for the get organizations organization databases database branches branch backups operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams struct {

	/* Branch.

	   The name of the branch
	*/
	Branch string

	/* Database.

	   The name of the database the branch belongs to
	*/
	Database string

	/* Organization.

	   The name of the organization the branch belongs to
	*/
	Organization string

	/* Page.

	   If provided, specifies the page offset of returned results

	   Default: 1
	*/
	Page *float64

	/* PerPage.

	   If provided, specifies the number of returned results

	   Default: 25
	*/
	PerPage *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organizations organization databases database branches branch backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithDefaults() *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organizations organization databases database branches branch backups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetDefaults() {
	var (
		pageDefault = float64(1)

		perPageDefault = float64(25)
	)

	val := GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams{
		Page:    &pageDefault,
		PerPage: &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithBranch(branch string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDatabase adds the database to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithDatabase(database string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetDatabase(database string) {
	o.Database = database
}

// WithOrganization adds the organization to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithOrganization(organization string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPage adds the page to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithPage(page *float64) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetPage(page *float64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WithPerPage(perPage *float64) *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get organizations organization databases database branches branch backups params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) SetPerPage(perPage *float64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesBranchBackupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage float64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatFloat64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage float64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatFloat64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
