// Code generated by go-swagger; DO NOT EDIT.

package database_branch_passwords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams() *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithTimeout creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams{
		timeout: timeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithContext creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams object
// with the ability to set a context for a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams{
		Context: ctx,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithHTTPClient creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParamsWithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams{
		HTTPClient: client,
	}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams contains all the parameters to send to the API endpoint

	for the post organizations organization databases database branches branch passwords id renew operation.

	Typically these are written to a http.Request.
*/
type PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams struct {

	/* Branch.

	   The name of the branch the password belongs to
	*/
	Branch string

	/* Database.

	   The name of the database the password belongs to
	*/
	Database string

	/* ID.

	   The ID of the password
	*/
	ID string

	/* Organization.

	   The name of the organization the password belongs to
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organizations organization databases database branches branch passwords id renew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithDefaults() *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organizations organization databases database branches branch passwords id renew params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithBranch(branch string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetBranch(branch string) {
	o.Branch = branch
}

// WithDatabase adds the database to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithDatabase(database string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetDatabase(database string) {
	o.Database = database
}

// WithID adds the id to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithID(id string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetID(id string) {
	o.ID = id
}

// WithOrganization adds the organization to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WithOrganization(organization string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post organizations organization databases database branches branch passwords id renew params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesBranchPasswordsIDRenewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch
	if err := r.SetPathParam("branch", o.Branch); err != nil {
		return err
	}

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
