// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationsOrganizationDatabasesParams creates a new GetOrganizationsOrganizationDatabasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationsOrganizationDatabasesParams() *GetOrganizationsOrganizationDatabasesParams {
	return &GetOrganizationsOrganizationDatabasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesParamsWithTimeout creates a new GetOrganizationsOrganizationDatabasesParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationsOrganizationDatabasesParamsWithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesParams {
	return &GetOrganizationsOrganizationDatabasesParams{
		timeout: timeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesParamsWithContext creates a new GetOrganizationsOrganizationDatabasesParams object
// with the ability to set a context for a request.
func NewGetOrganizationsOrganizationDatabasesParamsWithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesParams {
	return &GetOrganizationsOrganizationDatabasesParams{
		Context: ctx,
	}
}

// NewGetOrganizationsOrganizationDatabasesParamsWithHTTPClient creates a new GetOrganizationsOrganizationDatabasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationsOrganizationDatabasesParamsWithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesParams {
	return &GetOrganizationsOrganizationDatabasesParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationsOrganizationDatabasesParams contains all the parameters to send to the API endpoint

	for the get organizations organization databases operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationsOrganizationDatabasesParams struct {

	/* Organization.

	   The name of the organization the database belongs to
	*/
	Organization string

	/* Page.

	   If provided, specifies the page offset of returned results

	   Default: 1
	*/
	Page *float64

	/* PerPage.

	   If provided, specifies the number of returned results

	   Default: 25
	*/
	PerPage *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organizations organization databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesParams) WithDefaults() *GetOrganizationsOrganizationDatabasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organizations organization databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesParams) SetDefaults() {
	var (
		pageDefault = float64(1)

		perPageDefault = float64(25)
	)

	val := GetOrganizationsOrganizationDatabasesParams{
		Page:    &pageDefault,
		PerPage: &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithOrganization(organization string) *GetOrganizationsOrganizationDatabasesParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPage adds the page to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithPage(page *float64) *GetOrganizationsOrganizationDatabasesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetPage(page *float64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) WithPerPage(perPage *float64) *GetOrganizationsOrganizationDatabasesParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get organizations organization databases params
func (o *GetOrganizationsOrganizationDatabasesParams) SetPerPage(perPage *float64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationsOrganizationDatabasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage float64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatFloat64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage float64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatFloat64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
