// Code generated by go-swagger; DO NOT EDIT.

package databases

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationsOrganizationDatabasesParams creates a new PostOrganizationsOrganizationDatabasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationsOrganizationDatabasesParams() *PostOrganizationsOrganizationDatabasesParams {
	return &PostOrganizationsOrganizationDatabasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesParamsWithTimeout creates a new PostOrganizationsOrganizationDatabasesParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationsOrganizationDatabasesParamsWithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesParams {
	return &PostOrganizationsOrganizationDatabasesParams{
		timeout: timeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesParamsWithContext creates a new PostOrganizationsOrganizationDatabasesParams object
// with the ability to set a context for a request.
func NewPostOrganizationsOrganizationDatabasesParamsWithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesParams {
	return &PostOrganizationsOrganizationDatabasesParams{
		Context: ctx,
	}
}

// NewPostOrganizationsOrganizationDatabasesParamsWithHTTPClient creates a new PostOrganizationsOrganizationDatabasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationsOrganizationDatabasesParamsWithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesParams {
	return &PostOrganizationsOrganizationDatabasesParams{
		HTTPClient: client,
	}
}

/*
PostOrganizationsOrganizationDatabasesParams contains all the parameters to send to the API endpoint

	for the post organizations organization databases operation.

	Typically these are written to a http.Request.
*/
type PostOrganizationsOrganizationDatabasesParams struct {

	// Body.
	Body PostOrganizationsOrganizationDatabasesBody

	/* Organization.

	   The name of the organization the database belongs to
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organizations organization databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesParams) WithDefaults() *PostOrganizationsOrganizationDatabasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organizations organization databases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) WithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) WithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) WithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) WithBody(body PostOrganizationsOrganizationDatabasesBody) *PostOrganizationsOrganizationDatabasesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) SetBody(body PostOrganizationsOrganizationDatabasesBody) {
	o.Body = body
}

// WithOrganization adds the organization to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) WithOrganization(organization string) *PostOrganizationsOrganizationDatabasesParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post organizations organization databases params
func (o *PostOrganizationsOrganizationDatabasesParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationsOrganizationDatabasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
