// Code generated by go-swagger; DO NOT EDIT.

package database_branches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams creates a new DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithTimeout creates a new DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a timeout on a request.
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithTimeout(timeout time.Duration) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		timeout: timeout,
	}
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithContext creates a new DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a context for a request.
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithContext(ctx context.Context) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		Context: ctx,
	}
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithHTTPClient creates a new DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithHTTPClient(client *http.Client) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		HTTPClient: client,
	}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams contains all the parameters to send to the API endpoint

	for the delete organizations organization databases database branches name operation.

	Typically these are written to a http.Request.
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams struct {

	/* Database.

	   The name of the database the branch belongs to
	*/
	Database string

	/* Name.

	   The name of the branch
	*/
	Name string

	/* Organization.

	   The name of the organization the branch belongs to
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete organizations organization databases database branches name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithDefaults() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete organizations organization databases database branches name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithTimeout(timeout time.Duration) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithContext(ctx context.Context) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithHTTPClient(client *http.Client) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDatabase adds the database to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithDatabase(database string) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetDatabase(database string) {
	o.Database = database
}

// WithName adds the name to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithName(name string) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetName(name string) {
	o.Name = name
}

// WithOrganization adds the organization to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithOrganization(organization string) *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the delete organizations organization databases database branches name params
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
