// Code generated by go-swagger; DO NOT EDIT.

package database_branches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameReader is a Reader for the DeleteOrganizationsOrganizationDatabasesDatabaseBranchesName structure.
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /organizations/{organization}/databases/{database}/branches/{name}] delete_organizations_organization_databases_database_branches_name", response, response.Code())
	}
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent describes a response with status code 204, with default header values.

Delete a branch
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches name no content response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete organizations organization databases database branches name no content response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches name no content response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organizations organization databases database branches name no content response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches name no content response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete organizations organization databases database branches name no content response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) Code() int {
	return 204
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent ", 204)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent ", 204)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches name unauthorized response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches name unauthorized response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches name unauthorized response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches name unauthorized response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches name unauthorized response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete organizations organization databases database branches name unauthorized response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) Code() int {
	return 401
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized ", 401)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized ", 401)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches name forbidden response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches name forbidden response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches name forbidden response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches name forbidden response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches name forbidden response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete organizations organization databases database branches name forbidden response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) Code() int {
	return 403
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden ", 403)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden ", 403)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches name not found response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches name not found response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches name not found response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete organizations organization databases database branches name not found response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete organizations organization databases database branches name not found response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete organizations organization databases database branches name not found response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) Code() int {
	return 404
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound ", 404)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound ", 404)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError creates a DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError with default headers values
func NewDeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError() *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError {
	return &DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError{}
}

/*
DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError struct {
}

// IsSuccess returns true when this delete organizations organization databases database branches name internal server error response has a 2xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete organizations organization databases database branches name internal server error response has a 3xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete organizations organization databases database branches name internal server error response has a 4xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete organizations organization databases database branches name internal server error response has a 5xx status code
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete organizations organization databases database branches name internal server error response a status code equal to that given
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete organizations organization databases database branches name internal server error response
func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) Code() int {
	return 500
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError ", 500)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /organizations/{organization}/databases/{database}/branches/{name}][%d] deleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError ", 500)
}

func (o *DeleteOrganizationsOrganizationDatabasesDatabaseBranchesNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
