// Code generated by go-swagger; DO NOT EDIT.

package database_branches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams() *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithTimeout creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		timeout: timeout,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithContext creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a context for a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		Context: ctx,
	}
}

// NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithHTTPClient creates a new GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationsOrganizationDatabasesDatabaseBranchesNameParamsWithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	return &GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams contains all the parameters to send to the API endpoint

	for the get organizations organization databases database branches name operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams struct {

	/* Database.

	   The name of the database the branch belongs to
	*/
	Database string

	/* Name.

	   The name of the branch
	*/
	Name string

	/* Organization.

	   The name of the organization the branch belongs to
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organizations organization databases database branches name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithDefaults() *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organizations organization databases database branches name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithTimeout(timeout time.Duration) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithContext(ctx context.Context) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithHTTPClient(client *http.Client) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDatabase adds the database to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithDatabase(database string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetDatabase(database string) {
	o.Database = database
}

// WithName adds the name to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithName(name string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetName(name string) {
	o.Name = name
}

// WithOrganization adds the organization to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WithOrganization(organization string) *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get organizations organization databases database branches name params
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationsOrganizationDatabasesDatabaseBranchesNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
