// Code generated by go-swagger; DO NOT EDIT.

package database_branches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParams creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParams() *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithTimeout creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesParams object
// with the ability to set a timeout on a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesParams{
		timeout: timeout,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithContext creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesParams object
// with the ability to set a context for a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesParams{
		Context: ctx,
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithHTTPClient creates a new PostOrganizationsOrganizationDatabasesDatabaseBranchesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostOrganizationsOrganizationDatabasesDatabaseBranchesParamsWithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	return &PostOrganizationsOrganizationDatabasesDatabaseBranchesParams{
		HTTPClient: client,
	}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseBranchesParams contains all the parameters to send to the API endpoint

	for the post organizations organization databases database branches operation.

	Typically these are written to a http.Request.
*/
type PostOrganizationsOrganizationDatabasesDatabaseBranchesParams struct {

	// Body.
	Body PostOrganizationsOrganizationDatabasesDatabaseBranchesBody

	/* Database.

	   The name of the database the branch belongs to
	*/
	Database string

	/* Organization.

	   The name of the organization the branch belongs to
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post organizations organization databases database branches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithDefaults() *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post organizations organization databases database branches params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithTimeout(timeout time.Duration) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithContext(ctx context.Context) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithHTTPClient(client *http.Client) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithBody(body PostOrganizationsOrganizationDatabasesDatabaseBranchesBody) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetBody(body PostOrganizationsOrganizationDatabasesDatabaseBranchesBody) {
	o.Body = body
}

// WithDatabase adds the database to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithDatabase(database string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetDatabase(database string) {
	o.Database = database
}

// WithOrganization adds the organization to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WithOrganization(organization string) *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the post organizations organization databases database branches params
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PostOrganizationsOrganizationDatabasesDatabaseBranchesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
