// Code generated by go-swagger; DO NOT EDIT.

package o_auth_applications

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOrganizationsOrganizationOauthApplicationsParams creates a new GetOrganizationsOrganizationOauthApplicationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrganizationsOrganizationOauthApplicationsParams() *GetOrganizationsOrganizationOauthApplicationsParams {
	return &GetOrganizationsOrganizationOauthApplicationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrganizationsOrganizationOauthApplicationsParamsWithTimeout creates a new GetOrganizationsOrganizationOauthApplicationsParams object
// with the ability to set a timeout on a request.
func NewGetOrganizationsOrganizationOauthApplicationsParamsWithTimeout(timeout time.Duration) *GetOrganizationsOrganizationOauthApplicationsParams {
	return &GetOrganizationsOrganizationOauthApplicationsParams{
		timeout: timeout,
	}
}

// NewGetOrganizationsOrganizationOauthApplicationsParamsWithContext creates a new GetOrganizationsOrganizationOauthApplicationsParams object
// with the ability to set a context for a request.
func NewGetOrganizationsOrganizationOauthApplicationsParamsWithContext(ctx context.Context) *GetOrganizationsOrganizationOauthApplicationsParams {
	return &GetOrganizationsOrganizationOauthApplicationsParams{
		Context: ctx,
	}
}

// NewGetOrganizationsOrganizationOauthApplicationsParamsWithHTTPClient creates a new GetOrganizationsOrganizationOauthApplicationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrganizationsOrganizationOauthApplicationsParamsWithHTTPClient(client *http.Client) *GetOrganizationsOrganizationOauthApplicationsParams {
	return &GetOrganizationsOrganizationOauthApplicationsParams{
		HTTPClient: client,
	}
}

/*
GetOrganizationsOrganizationOauthApplicationsParams contains all the parameters to send to the API endpoint

	for the get organizations organization oauth applications operation.

	Typically these are written to a http.Request.
*/
type GetOrganizationsOrganizationOauthApplicationsParams struct {

	/* Organization.

	   The name of the organization the OAuth applications belong to
	*/
	Organization string

	/* Page.

	   If provided, specifies the page offset of returned results

	   Default: 1
	*/
	Page *float64

	/* PerPage.

	   If provided, specifies the number of returned results

	   Default: 25
	*/
	PerPage *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get organizations organization oauth applications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithDefaults() *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get organizations organization oauth applications params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetDefaults() {
	var (
		pageDefault = float64(1)

		perPageDefault = float64(25)
	)

	val := GetOrganizationsOrganizationOauthApplicationsParams{
		Page:    &pageDefault,
		PerPage: &perPageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithTimeout(timeout time.Duration) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithContext(ctx context.Context) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithHTTPClient(client *http.Client) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrganization adds the organization to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithOrganization(organization string) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WithPage adds the page to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithPage(page *float64) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetPage(page *float64) {
	o.Page = page
}

// WithPerPage adds the perPage to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WithPerPage(perPage *float64) *GetOrganizationsOrganizationOauthApplicationsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get organizations organization oauth applications params
func (o *GetOrganizationsOrganizationOauthApplicationsParams) SetPerPage(perPage *float64) {
	o.PerPage = perPage
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrganizationsOrganizationOauthApplicationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if o.Page != nil {

		// query param page
		var qrPage float64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatFloat64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage float64

		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatFloat64(qrPerPage)
		if qPerPage != "" {

			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
