// Code generated by go-swagger; DO NOT EDIT.

package deploy_requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployReader is a Reader for the PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeploy structure.
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy] post_organizations_organization_databases_database_deploy-requests_number_deploy", response, response.Code())
	}
}

// NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK creates a PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK with default headers values
func NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK {
	return &PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK{}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK describes a response with status code 200, with default header values.

Returns the deployed deploy request
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK struct {
	Payload *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody
}

// IsSuccess returns true when this post organizations organization databases database deploy requests number deploy o k response has a 2xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post organizations organization databases database deploy requests number deploy o k response has a 3xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post organizations organization databases database deploy requests number deploy o k response has a 4xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post organizations organization databases database deploy requests number deploy o k response has a 5xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post organizations organization databases database deploy requests number deploy o k response a status code equal to that given
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post organizations organization databases database deploy requests number deploy o k response
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) Code() int {
	return 200
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK  %+v", 200, o.Payload)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) String() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK  %+v", 200, o.Payload)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) GetPayload() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody {
	return o.Payload
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized creates a PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized with default headers values
func NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized {
	return &PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized{}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized struct {
}

// IsSuccess returns true when this post organizations organization databases database deploy requests number deploy unauthorized response has a 2xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post organizations organization databases database deploy requests number deploy unauthorized response has a 3xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post organizations organization databases database deploy requests number deploy unauthorized response has a 4xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post organizations organization databases database deploy requests number deploy unauthorized response has a 5xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post organizations organization databases database deploy requests number deploy unauthorized response a status code equal to that given
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post organizations organization databases database deploy requests number deploy unauthorized response
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) Code() int {
	return 401
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized ", 401)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) String() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized ", 401)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden creates a PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden with default headers values
func NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden {
	return &PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden{}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden struct {
}

// IsSuccess returns true when this post organizations organization databases database deploy requests number deploy forbidden response has a 2xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post organizations organization databases database deploy requests number deploy forbidden response has a 3xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post organizations organization databases database deploy requests number deploy forbidden response has a 4xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this post organizations organization databases database deploy requests number deploy forbidden response has a 5xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this post organizations organization databases database deploy requests number deploy forbidden response a status code equal to that given
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the post organizations organization databases database deploy requests number deploy forbidden response
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) Code() int {
	return 403
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden ", 403)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) String() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden ", 403)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound creates a PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound with default headers values
func NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound {
	return &PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound{}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound struct {
}

// IsSuccess returns true when this post organizations organization databases database deploy requests number deploy not found response has a 2xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post organizations organization databases database deploy requests number deploy not found response has a 3xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post organizations organization databases database deploy requests number deploy not found response has a 4xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post organizations organization databases database deploy requests number deploy not found response has a 5xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post organizations organization databases database deploy requests number deploy not found response a status code equal to that given
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post organizations organization databases database deploy requests number deploy not found response
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) Code() int {
	return 404
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound ", 404)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) String() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound ", 404)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError creates a PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError with default headers values
func NewPostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError() *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError {
	return &PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError{}
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError struct {
}

// IsSuccess returns true when this post organizations organization databases database deploy requests number deploy internal server error response has a 2xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post organizations organization databases database deploy requests number deploy internal server error response has a 3xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post organizations organization databases database deploy requests number deploy internal server error response has a 4xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post organizations organization databases database deploy requests number deploy internal server error response has a 5xx status code
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post organizations organization databases database deploy requests number deploy internal server error response a status code equal to that given
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post organizations organization databases database deploy requests number deploy internal server error response
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) Code() int {
	return 500
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) Error() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError ", 500)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) String() string {
	return fmt.Sprintf("[POST /organizations/{organization}/databases/{database}/deploy-requests/{number}/deploy][%d] postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError ", 500)
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody post organizations organization databases database deploy requests number deploy o k body
swagger:model PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody struct {

	// actor
	// Required: true
	Actor *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor `json:"actor"`

	// Whether or not the deploy request is approved
	// Required: true
	Approved *bool `json:"approved"`

	// The name of the branch the deploy request was created from
	// Required: true
	Branch *string `json:"branch"`

	// Whether or not the deploy request branch was deleted
	// Required: true
	BranchDeleted *bool `json:"branch_deleted"`

	// When the deploy request branch was deleted
	// Required: true
	BranchDeletedAt *string `json:"branch_deleted_at"`

	// branch deleted by
	// Required: true
	BranchDeletedBy *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy `json:"branch_deleted_by"`

	// The id of the branch the deploy request was created from
	// Required: true
	BranchID *string `json:"branch_id"`

	// When the deploy request was closed
	// Required: true
	ClosedAt *string `json:"closed_at"`

	// closed by
	// Required: true
	ClosedBy *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy `json:"closed_by"`

	// When the deploy request was created
	// Required: true
	CreatedAt *string `json:"created_at"`

	// When the deploy request was deployed
	// Required: true
	DeployedAt *string `json:"deployed_at"`

	// The deployment state of the deploy request
	// Required: true
	// Enum: [pending ready no_changes queued submitting in_progress pending_cutover in_progress_vschema in_progress_cancel in_progress_cutover complete complete_cancel complete_error complete_pending_revert in_progress_revert complete_revert complete_revert_error cancelled error]
	DeploymentState *string `json:"deployment_state"`

	// The HTML body of the deploy request
	// Required: true
	HTMLBody *string `json:"html_body"`

	// The PlanetScale app address for the deploy request
	// Required: true
	HTMLURL *string `json:"html_url"`

	// The ID of the deploy request
	// Required: true
	ID *string `json:"id"`

	// The name of the branch the deploy request will be merged into
	// Required: true
	IntoBranch *string `json:"into_branch"`

	// The number of shards the branch the deploy request will be merged into has
	// Required: true
	IntoBranchShardCount *float64 `json:"into_branch_shard_count"`

	// Whether or not the branch the deploy request will be merged into is sharded
	// Required: true
	IntoBranchSharded *bool `json:"into_branch_sharded"`

	// Notes on the deploy request
	// Required: true
	Notes *string `json:"notes"`

	// The number of the deploy request
	// Required: true
	Number *float64 `json:"number"`

	// Whether the deploy request is open or closed
	// Required: true
	// Enum: [open closed]
	State *string `json:"state"`

	// When the deploy request was last updated
	// Required: true
	UpdatedAt *string `json:"updated_at"`
}

// Validate validates this post organizations organization databases database deploy requests number deploy o k body
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateActor(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateApproved(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBranch(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBranchDeleted(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBranchDeletedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBranchDeletedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBranchID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateClosedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateClosedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeployedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeploymentState(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHTMLBody(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateHTMLURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIntoBranch(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIntoBranchShardCount(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIntoBranchSharded(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNotes(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNumber(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateActor(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"actor", "body", o.Actor); err != nil {
		return err
	}

	if o.Actor != nil {
		if err := o.Actor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "actor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "actor")
			}
			return err
		}
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateApproved(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"approved", "body", o.Approved); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateBranch(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch", "body", o.Branch); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateBranchDeleted(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted", "body", o.BranchDeleted); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateBranchDeletedAt(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted_at", "body", o.BranchDeletedAt); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateBranchDeletedBy(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted_by", "body", o.BranchDeletedBy); err != nil {
		return err
	}

	if o.BranchDeletedBy != nil {
		if err := o.BranchDeletedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "branch_deleted_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "branch_deleted_by")
			}
			return err
		}
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateBranchID(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_id", "body", o.BranchID); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateClosedAt(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"closed_at", "body", o.ClosedAt); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateClosedBy(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"closed_by", "body", o.ClosedBy); err != nil {
		return err
	}

	if o.ClosedBy != nil {
		if err := o.ClosedBy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "closed_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "closed_by")
			}
			return err
		}
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"created_at", "body", o.CreatedAt); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateDeployedAt(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"deployed_at", "body", o.DeployedAt); err != nil {
		return err
	}

	return nil
}

var postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeDeploymentStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending","ready","no_changes","queued","submitting","in_progress","pending_cutover","in_progress_vschema","in_progress_cancel","in_progress_cutover","complete","complete_cancel","complete_error","complete_pending_revert","in_progress_revert","complete_revert","complete_revert_error","cancelled","error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeDeploymentStatePropEnum = append(postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeDeploymentStatePropEnum, v)
	}
}

const (

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStatePending captures enum value "pending"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStatePending string = "pending"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateReady captures enum value "ready"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateReady string = "ready"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateNoChanges captures enum value "no_changes"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateNoChanges string = "no_changes"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateQueued captures enum value "queued"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateQueued string = "queued"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateSubmitting captures enum value "submitting"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateSubmitting string = "submitting"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgress captures enum value "in_progress"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgress string = "in_progress"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStatePendingCutover captures enum value "pending_cutover"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStatePendingCutover string = "pending_cutover"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressVschema captures enum value "in_progress_vschema"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressVschema string = "in_progress_vschema"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressCancel captures enum value "in_progress_cancel"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressCancel string = "in_progress_cancel"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressCutover captures enum value "in_progress_cutover"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressCutover string = "in_progress_cutover"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateComplete captures enum value "complete"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateComplete string = "complete"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteCancel captures enum value "complete_cancel"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteCancel string = "complete_cancel"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteError captures enum value "complete_error"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteError string = "complete_error"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompletePendingRevert captures enum value "complete_pending_revert"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompletePendingRevert string = "complete_pending_revert"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressRevert captures enum value "in_progress_revert"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateInProgressRevert string = "in_progress_revert"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteRevert captures enum value "complete_revert"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteRevert string = "complete_revert"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteRevertError captures enum value "complete_revert_error"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCompleteRevertError string = "complete_revert_error"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCancelled captures enum value "cancelled"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateCancelled string = "cancelled"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateError captures enum value "error"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyDeploymentStateError string = "error"
)

// prop value enum
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateDeploymentStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeDeploymentStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateDeploymentState(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"deployment_state", "body", o.DeploymentState); err != nil {
		return err
	}

	// value enum
	if err := o.validateDeploymentStateEnum("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"deployment_state", "body", *o.DeploymentState); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateHTMLBody(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"html_body", "body", o.HTMLBody); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateHTMLURL(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"html_url", "body", o.HTMLURL); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateIntoBranch(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"into_branch", "body", o.IntoBranch); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateIntoBranchShardCount(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"into_branch_shard_count", "body", o.IntoBranchShardCount); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateIntoBranchSharded(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"into_branch_sharded", "body", o.IntoBranchSharded); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateNotes(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"notes", "body", o.Notes); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateNumber(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"number", "body", o.Number); err != nil {
		return err
	}

	return nil
}

var postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["open","closed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeStatePropEnum = append(postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeStatePropEnum, v)
	}
}

const (

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyStateOpen captures enum value "open"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyStateOpen string = "open"

	// PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyStateClosed captures enum value "closed"
	PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyStateClosed string = "closed"
)

// prop value enum
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateState(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"state", "body", o.State); err != nil {
		return err
	}

	// value enum
	if err := o.validateStateEnum("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"state", "body", *o.State); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"updated_at", "body", o.UpdatedAt); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this post organizations organization databases database deploy requests number deploy o k body based on the context it is used
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateActor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateBranchDeletedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateClosedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) contextValidateActor(ctx context.Context, formats strfmt.Registry) error {

	if o.Actor != nil {

		if err := o.Actor.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "actor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "actor")
			}
			return err
		}
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) contextValidateBranchDeletedBy(ctx context.Context, formats strfmt.Registry) error {

	if o.BranchDeletedBy != nil {

		if err := o.BranchDeletedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "branch_deleted_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "branch_deleted_by")
			}
			return err
		}
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) contextValidateClosedBy(ctx context.Context, formats strfmt.Registry) error {

	if o.ClosedBy != nil {

		if err := o.ClosedBy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "closed_by")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK" + "." + "closed_by")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody) UnmarshalBinary(b []byte) error {
	var res PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor post organizations organization databases database deploy requests number deploy o k body actor
swagger:model PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor struct {

	// The URL of the actor's avatar
	// Required: true
	AvatarURL *string `json:"avatar_url"`

	// The name of the actor
	// Required: true
	DisplayName *string `json:"display_name"`

	// The ID of the actor
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this post organizations organization databases database deploy requests number deploy o k body actor
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAvatarURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) validateAvatarURL(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"actor"+"."+"avatar_url", "body", o.AvatarURL); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) validateDisplayName(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"actor"+"."+"display_name", "body", o.DisplayName); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) validateID(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"actor"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post organizations organization databases database deploy requests number deploy o k body actor based on context it is used
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor) UnmarshalBinary(b []byte) error {
	var res PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyActor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy post organizations organization databases database deploy requests number deploy o k body branch deleted by
swagger:model PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy struct {

	// The URL of the actor's avatar
	// Required: true
	AvatarURL *string `json:"avatar_url"`

	// The name of the actor
	// Required: true
	DisplayName *string `json:"display_name"`

	// The ID of the actor
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this post organizations organization databases database deploy requests number deploy o k body branch deleted by
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAvatarURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) validateAvatarURL(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted_by"+"."+"avatar_url", "body", o.AvatarURL); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) validateDisplayName(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted_by"+"."+"display_name", "body", o.DisplayName); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) validateID(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"branch_deleted_by"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post organizations organization databases database deploy requests number deploy o k body branch deleted by based on context it is used
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy) UnmarshalBinary(b []byte) error {
	var res PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyBranchDeletedBy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy post organizations organization databases database deploy requests number deploy o k body closed by
swagger:model PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy
*/
type PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy struct {

	// The URL of the actor's avatar
	// Required: true
	AvatarURL *string `json:"avatar_url"`

	// The name of the actor
	// Required: true
	DisplayName *string `json:"display_name"`

	// The ID of the actor
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this post organizations organization databases database deploy requests number deploy o k body closed by
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAvatarURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDisplayName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) validateAvatarURL(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"closed_by"+"."+"avatar_url", "body", o.AvatarURL); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) validateDisplayName(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"closed_by"+"."+"display_name", "body", o.DisplayName); err != nil {
		return err
	}

	return nil
}

func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) validateID(formats strfmt.Registry) error {

	if err := validate.Required("postOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOK"+"."+"closed_by"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post organizations organization databases database deploy requests number deploy o k body closed by based on context it is used
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy) UnmarshalBinary(b []byte) error {
	var res PostOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberDeployOKBodyClosedBy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
