// Code generated by go-swagger; DO NOT EDIT.

package deploy_requests

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams creates a new PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams() *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	return &PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithTimeout creates a new PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams object
// with the ability to set a timeout on a request.
func NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithTimeout(timeout time.Duration) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	return &PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams{
		timeout: timeout,
	}
}

// NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithContext creates a new PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams object
// with the ability to set a context for a request.
func NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithContext(ctx context.Context) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	return &PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams{
		Context: ctx,
	}
}

// NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithHTTPClient creates a new PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParamsWithHTTPClient(client *http.Client) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	return &PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams{
		HTTPClient: client,
	}
}

/*
PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams contains all the parameters to send to the API endpoint

	for the put organizations organization databases database deploy requests number auto apply operation.

	Typically these are written to a http.Request.
*/
type PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams struct {

	// Body.
	Body PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyBody

	/* Database.

	   The name of the deploy request's database
	*/
	Database string

	/* Number.

	   The number of the deploy request
	*/
	Number string

	/* Organization.

	   The name of the deploy request's organization
	*/
	Organization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put organizations organization databases database deploy requests number auto apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithDefaults() *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put organizations organization databases database deploy requests number auto apply params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithTimeout(timeout time.Duration) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithContext(ctx context.Context) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithHTTPClient(client *http.Client) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithBody(body PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyBody) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetBody(body PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyBody) {
	o.Body = body
}

// WithDatabase adds the database to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithDatabase(database string) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetDatabase(database)
	return o
}

// SetDatabase adds the database to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetDatabase(database string) {
	o.Database = database
}

// WithNumber adds the number to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithNumber(number string) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetNumber(number string) {
	o.Number = number
}

// WithOrganization adds the organization to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WithOrganization(organization string) *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams {
	o.SetOrganization(organization)
	return o
}

// SetOrganization adds the organization to the put organizations organization databases database deploy requests number auto apply params
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) SetOrganization(organization string) {
	o.Organization = organization
}

// WriteToRequest writes these params to a swagger request
func (o *PutOrganizationsOrganizationDatabasesDatabaseDeployRequestsNumberAutoApplyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param database
	if err := r.SetPathParam("database", o.Database); err != nil {
		return err
	}

	// path param number
	if err := r.SetPathParam("number", o.Number); err != nil {
		return err
	}

	// path param organization
	if err := r.SetPathParam("organization", o.Organization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
